# Generated by Django 2.1.2 on 2019-04-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='operator_hotel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hotel Encargado'),
        ),
    ]
