# Generated by Django 2.1.2 on 2019-04-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_operator_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='operator_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete='Hotel Encargado', to='reservations.Hotels'),
        ),
    ]
