# Generated by Django 2.1.3 on 2019-04-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190425_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='operator_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.Hotels'),
        ),
    ]
