# Generated by Django 2.1.2 on 2018-10-10 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ubication', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_guest', models.CharField(max_length=255)),
                ('telephone_guest', models.CharField(max_length=255)),
                ('city_guest', models.CharField(blank=True, max_length=255, null=True)),
                ('id_guest', models.CharField(max_length=255)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('nights', models.IntegerField()),
                ('number_adults', models.PositiveIntegerField(default=1)),
                ('number_childs', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('rate', models.FloatField()),
                ('commission', models.FloatField()),
                ('total', models.FloatField()),
                ('total_amc', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictionHotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_on', models.DateTimeField()),
                ('date_off', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.Hotels')),
                ('id_user_modify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_modify_restriction', to=settings.AUTH_USER_MODEL)),
                ('id_user_register', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_register_restriction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.Hotels')),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='id_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.Rooms'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='id_user_modify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_modify_reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservations',
            name='id_user_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_register_reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
