#!/bin/bash
NAME="devamc"
VIRTUALENV="/home/devamc/.venv"
DJANGODIR="/home/devamc/amc/"
USER=devamc 
GROUP=sudo
NUM_WORKERS=3
DJANGO_WSGI_MODULE=amc.wsgi
echo "Starting $NAME as whoami"
cd $VIRTUALENV
source bin/activate
cd $DJANGODIR
export AMC_SECRET_KEY="#fm+fo)h_gz43s826m4$a6b(=od(u(%dqhxyw-!a28j=-gi-%6"
export AMC_DB_NAME="amc"
export AMC_DB_USER="root"
export AMC_DB_PASSWORD="9411"
export AMC_DB_PORT="5432"
export AMC_DB_HOST="localhost"
export DJANGO_SETTINGS_MODULE="amc.settings"
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
exec gunicorn ${DJANGO_WSGI_MODULE} \
    --workers $NUM_WORKERS \
    --user=$USER --group=$GROUP \
    --log-level=debug \
    --bind=127.0.0.1:8000
